# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71838bbbbd41c280ae713f072ea6ab26e5febe83f622243c6446a59abb312f20f7060e212c647d8635c74b0014d4a0c55956ae91f16159fa7f72e8b7cdb471e0

test:
  secret_key_base: a8f711f89823229b374d42b1ec2c17cdaf9ef99b497783b56361a3350f99828158a49dc59e06b4a281deaf6168904ed0e55fd0dfe317fd21c80248a60a6e9cc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
